services:
  db:
    image: mysql:latest # Correct database image
    container_name: web-fut
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=SPRINT_3brief2
      - MYSQL_USER=myuserr
      - MYSQL_PASSWORD=mypasswordd
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  www:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "./:/var/www/html"
    ports:
      - "8084:80"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    name: my_project_mysql_data